hello
hello
hello
Traceback (most recent call last):
  File "post.py", line 40, in <module>
    main()
  File "post.py", line 23, in main
    messages = slack.channels.history('C0HA24604')
  File "/usr/lib/python2.7/site-packages/slacker/__init__.py", line 191, in history
    'unreads': int(unreads)
  File "/usr/lib/python2.7/site-packages/slacker/__init__.py", line 66, in get
    return self._request(requests.get, api, **kwargs)
  File "/usr/lib/python2.7/site-packages/slacker/__init__.py", line 55, in _request
    **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
